# @package _global_
defaults:
  - star_seq2seq_block_diffusion
  - /datasets@datamodule.dataset_managers.train.lm: star_easy_train
  - /datasets@datamodule.dataset_managers.val.lm: star_easy_val
 # - /datasets@datamodule.dataset_managers.val.prediction: star_easy_val_pred
  - /datasets@datamodule.dataset_managers.test.lm: star_easy_test
  - /datasets@datamodule.dataset_managers.test.prediction: star_easy_test_pred
  - /datasets@datamodule.dataset_managers.predict.prediction: star_easy_val_pred

tags:
  dataset: star_easy_seq2seq

datamodule:
  dataset_managers:
    predict:
      prediction:
        stages:
          - predict
