_target_: block_diffusion.datamodule_block_diffusion.BlockDiffusionSeq2SeqPredCollator
input_block_size: ${oc.select:input_block_size,null}
block_size: ${block_size}
tokenizer: ${global_components:tokenizer}
noise_schedule: ${global_components:noise_schedule}
add_bos: output
add_eos: true
